# frozen_string_literal: true

ruby '3.2.0'

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'database_cleaner-active_record'
gem 'rake'
gem 'rubocop', require: false
gem 'rubycritic'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3', '~> 1.4'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
end
