ruby '3.2.0'

source "https://rubygems.org"

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem "sqlite3", "~> 1.4"
gem 'rake'
gem 'simplecov'
gem 'database_cleaner-active_record'

group :test, :development do
    gem 'rspec'
    gem 'rack-test'
end
